ToniA/arduino-heatpumpir

DaikinHeatpumpARC417IR.cpp, DaikinHeatpumpARC417IR.h
Tested and it works with PWM on duemilanove and on ESP8266.
I have developed the ARC417A3 driver on new files, because even the logic is the same, there are many differences (timing, fan code, temperature computation, template...). It seems to be difficult to merge the two Daikin drivers simply.
=> Add Daikin ARC417A3 remote control

MitsubishiHeavyHeatpumpIR.cpp, MitsubishiHeavyHeatpumpIR.h, README.md
I am adding the support for Mitsubishi Heavy Industries SRKXXZMP-S models (SRK25ZMP-S, SRK35ZMP-S, SRK45ZMP-S). Remote control part number is RKX502A001P. Thanks for your excellent library!
=> Adding support for Mitsubishi Heavy Industries SRKXXZMP-S

MitsubishiSEZKDXXHeatpumpIR.h
Removed the char 'a' in: "#define MitsubishiSEZKDXXaHeatpumpIR_h"
to:  "#define MitsubishiSEZKDXXHeatpumpIR_h" 
Causing duplicate declaration in IDE different from the arduino.
=> Typo into def flag

AUXHeatpumpIR.h, GreeHeatpumpIR.cpp, GreeHeatpumpIR.h, README.md, examples/simple/simple.ino, keywords.txt
Added support for these remotes based on the document published on that thread: [https://forum.mysensors.org/topic/4253/ac-ir-code-decrypting](url)
Tested to work with Tosot T18H-SN/I (remote control P/N YAA1FB).
Also added Hyundai Model H-AR21-07H (remote control P/N YKR-P/002E) confirmed as AUX (tested to work).
=> Support for YAA1FB, FAA1FB1, YB1F2 remotes

IRSenderPWM.cpp
Due to ATmeg8/8A does not have register "TCCR2A", using marco to bypss the related code.
PS: ATmega8/8A can use PWM pin 9 or 10 in IRSenderPWM mode ONLY.
=> Due to ATmeg8/8A does not have register "TCCR2A"

AUXHeatpumpIR.cpp
based on https://github.com/ToniA/arduino-heatpumpir/issues/71#issuecomment-506924875
I realized that the off command is hardcoded to HEAT and not all AUX has HEAT mode. Changing to AUTO should do the work.
=> change operatingMode to AUTO

IRSender.h, IRSenderESP32.cpp, IRSenderPWM.cpp
ESP32 support addedwith native PWM
Tested on R51M/E remote control
Example:
`heatpumpIR = new R51MHeatpumpIR();
IRSenderESP32 irSender(2, 0);  
heatpumpIR->send(irSender, POWER_ON, MODE_COOL, FAN_2, 22, VDIR_UP, HDIR_AUTO);
`
=> ESP32 support added

MitsubishiHeatpumpIR.cpp, MitsubishiHeatpumpIR.h
Added support for MITSUBISHI KJ series heatpumps / remote control type SG161.
Also added a IR_DEBUG_PACKET define to be able to feedback and debug the IR packet as added text output to a browser, curl or other http request tool.
=> Support for MITSUBISHI KJ heatpumps (SG 161 0927 remote)

IRSenderPWM.cpp, ToshibaDaiseikaiHeatpumpIR.cpp, ToshibaDaiseikaiHeatpumpIR.h
- Fixed Arduino MEGA pins 44 and 45 not working
- Fixed Arduino MEGA pins 44, 45, 46 not working correctly (low range, inconsistent payload)
- Fixed Toshiba Daiseikai checksum calculation
- Adjusted Toshiba Daiseikai timings, pause space was for some reason mostly omitted, atleast on my Arduino MEGA, after the changes, pause space is never omitted, the proposed timings are verified with remote WH-H05JE on both: Raw-IR-decoder-for-Arduino and IRrecvDumpV2 from the IRremoteESP8266 project.
=> Enable Arduino Mega pins 44,45,46 + checksum calc fixes

README.md, SamsungHeatpumpIR.cpp, SamsungHeatpumpIR.h
This pull request is related to the issue #103.
It is a result of a reverse engineering to be able to control my Samsung AQV12MSAN airco/heater models by MySensors IR nodes. 
These MySensors nodes are using this splendid library of heatpumps to be able to control the airco's by, in my case, Home Assistant, a home domotica controller.
=> Adding supporting code for the Samsung AQV12MSAN model 

library.json
This PR means that:
- [https://platformio.org/lib/show/290/HeatpumpIR](https://platformio.org/lib/show/290/HeatpumpIR) will show the correct version.
- PlatformIO will automatically download the required library for ESP8266.
I am requesting this to make it easier to provide arduino-heatpumpir to users of esphome (see https://github.com/esphome/esphome/pull/1343)
Could you please also run `pio package publish` after merging these changes?
=> Added version and dependencies to library.json

GreeHeatpumpIR.cpp, GreeHeatpumpIR.h, examples/GreeTest/GreeYACTest/GreeYACTest.ino
A few changes coming in around Gree heatpumps.
1. Classes for GreeYAN, GreeYAA didn't actually implement their send() functions properly, that is fixed.
2. Added GreeYAC class and send with support for Horizontal Swing, I-Feel, and current temperature
3. Added example for testing GreeYAC class
I've tested this on a breadboard for the moment, with and IR receiver and it does appear to work. It'll need more testing which I'll carry out in the coming weeks, but I think this is good to merge right now.
CLOSES: #86
=> Add support for GreeYAC and I-Feel

GreeHeatpumpIR.cpp
Slight error with the model setup meant that everything worked perviously, but YAC features could not be set.
This PR correct the issue and proper uses the GRE_YAC model.
=> Fixing identifier for Gree YAC

README.md, VaillantHeatpumpIR.cpp, VaillantHeatpumpIR.h
Adds support for Vaillant VAI8 heat pumps (some kind of Gree YAA variant).
Supports all the essential features of the pump except iFeel. I have been running this on an ESP8266 ESP-01 board using *IRSenderIRremoteESP8266* (had no luck with the other IR send methods) for about a month with VAI8-025WNI.
=> Add support for Vaillant VAI8

GreeHeatpumpIR.cpp, GreeHeatpumpIR.h, HeatpumpIR.cpp, HeatpumpIR.h
Addresses an issues raised in #117.
The I-Feel message feature for Gree YAC devices uses a separate set of timings for the feature message.
I've been running this for the last year+ on my Gree device without issues, took me a little while and some other data in the Issue to confirm my suspicion that it was just the message (and not my device).
=> Adjust timings for Gree I-Feel messages

GreeHeatpumpIR.cpp
looks just like a typo, see the code =)
rechecked that with dumping the real RC - yes, 3rd byte is always 0x50, 2nd is 0x60/0x70 depending on turbo mode.
please bump/tag version for yourself, thank you.
=> fixed typo in GreeHeatpumpIR::sendGree for YAN variant

SamsungHeatpumpIR.cpp
The temperature range in this code is set to 16-27°C.
16°C as low level is correct, Lower temp is not possible in the communication-protocol.
On my Samsung MH035FPEA-unit the maximum temperature is 30°C. For heating mode it would be nice to set this from the arduino-control.
Matthias
=> Hardcoded Temperature-Range ist too small

GreeHeatpumpIR.cpp
Fixes #152 
Function overloading arguments weren't correct. turboMode/iFeelMode were being transposed.
=> Fixed Gree application of turboMode/iFeelMode

IRSenderESP32.cpp
This fixes compatibility with ESP32 Arduino 3.0, that includes Espressif IDF 5.1.x.
Features:
- Include low-level `gpio*` functions from IDF, no longer included by default
- Adjust code for changed IDF `ledc*` functions and signatures
- Backward compatible with current ESP32 Arduino 2.0.x (with ESP-IDF 4.x)
Edit: For full compatibility with Arduino 3.0, IRremoteESP8266 still needs some changes, as similar patches have been PR'ed there (based on Tasmota code-changes), but that's at this time not yet fully working...
=> [ESP32] Fix compatibility with ESP32 Arduino 3.0 and ESP-IDF 5.1.x

IRSender.cpp, IRSender.h, IRSenderESP32.cpp
Some development boards like M5Stick-C have inverted LED, so when pin HIGH - led is off , etc.
To support that we need minor changes in code, unfortunately i dont have other boards, but inverted LED can be added to other senders easily.
Tested on Gree A/C and M5Stick-C.
=> Add inverted LED support to IRSenderESP32

IRSenderPWM.cpp
This PR fixes a build issue with Libretiny (which is a ESPHome port for BK72xx and other microcontroller). This prevent building the faulty PWM file for a platform that's not supported.
=> Fix for building issue on libretiny

HeatpumpIRFactory.cpp
This change allows creating `greeyac` and `greeyt` controllers using `HeatpumpIRFactory::create`.
=> Update HeatpumpIRFactory to support greeyac and greeyt

HeatpumpIRFactory.cpp, HeatpumpIRFactory.h, IRSender.cpp, IRSender.h, NibeHeatpumpIR.cpp, NibeHeatpumpIR.h, README.md
Hey @ToniA 
I added support for the Nibe AG-WL10-4 heat pump. I guess it will also work for the AG-WT10, since the remote controls from the menu describe the same functions.
I tested all the main functions with my heat pump. 
My modified IRSender.h/.cpp should not affect any other modules, but allows to send single bits. Needed a way to send 90 bits. Hope this solution is fine with you otherwise I can also create a separate function.
I am not 100% sure if the mapping for the fan speed is correct.
There are also 5 bits in the message that I have not been able to decode. They seem to randomly change, even when sending the same messages. Hard coded the 5 bits to one of the observed bit patterns and tested it without any issues.
Let me know if there is anything else to adjust.
=> Add Support for Nibe Heatpump AG-WL10-4

library.json
The `IRremoteESP8266` library is compatible with ESP32/ESP8266
=> Remove unnecessary constraints

GreeHeatpumpIR.cpp, GreeHeatpumpIR.h
This adds support for the YAP protocol (based on the Gree YAP1F7 remote) with extended features of the Gree Pular AC series.
The YAP protocol is similar to all other Gree protocols, but has many subtle differences, e.g. a longer message and different timings.  To implement it in an elegant way without much code duplication, some parts of the existing Gree IR code had to be significantly refactored.
This work is heavily based on the work of Thijs Houtenbos (@thoutenbos) included in this commit:  https://github.com/ToniA/arduino-heatpumpir/commit/4addf28e57526b4dbcdddc560c3002420e68cd6c
=> Add support for Gree YAP protocol 

library.json
Platforms like BK72XX and RP2040 don't need IRremoteESP8266 as dependency. Platformio will not try to bring in it on other platforms (including libretiny) because the it is explicitly disallowed:
https://github.com/crankyoldgit/IRremoteESP8266/blob/9785cb910d2b8c81785afb58d76090cb57c5b2df/library.json#L49
So this will only install it for ESP.
More info: https://github.com/esphome/esphome/pull/6955#issuecomment-2188338667
@rob-deutsch
=> Only install IRremoteESP8266 dependency on ESP platforms

HeatpumpIRFactory.h
Unfortunately
```
airway
bgh_aud
panasonic_altdke
vaillantvai8
r51m
```
could not be added to ESPHome because /HeatpumpIRFactory.h is missing inclusion of their corresponding header files.
=> Add missing models to HeatpumpIRFactory.h

IRSenderESP32.cpp
In IRSenderESP32::mark we do setup PWM then send modulated carrier for specified time, then switch off back to GPIO mode. In old code switch off done using gpio_reset_pin() which doesn't work properly in Arduino-esp32 3+, as it wont detach it from ledc and return in GPIO mode (in Verbose mode it will complain about it).
What is worse, it doesn't turn off LED after sending IR codes, because digitalWrite doesnt work, so in boards where by design LED should have only short pulses it might lead to LED burnout (almost happened with me).
What does work, properly detaching from ledc and setting to GPIO output mode.
Additional node: i suggest to test for anybody else if it works, and on old arduino frameworks.
I verified this patch on my particular setup and it works very well.
=> IRSenderESP32: Fix LED pin switch between PWM and GPIO

NibeHeatpumpIR.cpp, NibeHeatpumpIR.h
Hey @ToniA,
a small update to the Nibe Heatpump code that I submitted earlier this year.
- I enable iFeel by default. For the case that no IFeel sensor is available the unit will use its internal build in sensor
- Adjusted the fan definitions to work correctly with ESP home
Are there any plans to release a new version of platformio? Would like to get this code into ESPHOME IR Remote Climate.
Greetings Fabian
=> Enable iFeel by default, fix fan control to be compatible with ESPHOME

HeatpumpIRFactory.cpp, PanasonicHeatpumpIR.cpp, PanasonicHeatpumpIR.h
This is a pull request to add a Panasonic EKE protocol.
This protocol is compatible with the following Panasonic units:
CS-E9PB4EA
CS-E12PB4EA
CU-E9PB4EA
CU-E12PB4EA
CS-ME9PB4EA
CS-ME12PB4EA
CS-ME18PB4EA
CS-ME21PB4EA
Using these remote controls:
A75C4347
A75C3208
Thanks to [ToniA](https://github.com/ToniA) and [germin8](https://github.com/germin8) who helped me:
[A75C3208 Remote](https://github.com/ToniA/arduino-heatpumpir/issues/185)
=> Adding Panasonic EKE protocol

IRSender.h, library.json
IRremoteESP8266 does not support Arduino 3x and hence HeatpumpIR can't support Arduino 3x. IRremoteESP8266 has had an Arduino 3x PR open for a while but seems the maintainer is gone. ESPHome cant move to a new version of Arduino atm because of this. 
Remove the dependency on IRremoteESP8266 for ESP32. It can be manually included if someone wants it on Arduino 2x.
=> Don't automatically install IRremoteESP8266 on ESP32

library.json
ESPHome added strict mode for ldf, and due to libretiny missing from the library.json here, it would not compile the library in.
=> Update library.json for libretiny support
